"""
This file is auto-generated by lume-genesis (`genesis.version4.manual`).

Do not hand-edit it.
"""
from __future__ import annotations
import dataclasses
from decimal import Decimal

from typing import Union
{%- if base_imports %}

from .base import {{ base_imports | join(", ") }}
{%- endif %}

Float = Union[Decimal, float]
{%- for name, element in manual.elements.items() %}
{%- if element.parameters | length %}


@dataclasses.dataclass
{%- if name in base_classes %}
class {{ name | capitalize }}({{ base_classes[name] }}):
{%- else %}
class {{ name | capitalize }}:
{%- endif %}
    r"""
    {%- if element.header %}
    {{ element.header | wordwrap | indent(4) }}
    {%- elif name in docstrings %}
    {{ docstrings[name] | wordwrap | indent(4) }}
    {%- else %}
    {{ name | capitalize }}
    {%- endif %}

    Attributes
    ----------
    {%- for param in element.parameters.values() %}
    {%- set type_ = type_map.get(param.type, param.type) %}
    {{ param.python_name }} : {{ type_ }}{% if not param.default is none %}, default={{ param.default | repr }}{% endif %}
        {{ param.description | wordwrap | indent(8) }}
    {%- endfor %}
    """
    {%- for param in element.parameters.values() %}
    {%- set type_ = type_map.get(param.type, param.type) %}
    {{ param.python_name }}: {{ type_ }} {%- if not param.default is none %} = {{ param.default | repr }}{% endif %}
    {%- endfor %}
{%- endif %}
{%- endfor %}
